### ISSUE TITLE
rustfmt 1.4.8 with rust 1.38.0: error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by devurandom** [rust-lang/rustfmt#3834]
rustfmt 1.4.8 fails to compile with rust 1.38.0:
```
[...]
   Compiling smallvec v0.6.10
     Running `CARGO_PKG_REPOSITORY='https://github.com/servo/rust-smallvec' CARGO=/usr/bin/cargo-1.38.0 CARGO_PKG_NAME=smallvec LD_LIBRARY_PATH='/tmp/portage/dev-util/rustfmt-1.4.8/work/rustfmt-1.4.8/target/release/deps:/usr/lib' CARGO_PKG_DESCRIPTION=''\''Small vector'\'' optimization: store up to a small number of items on the stack' CARGO_PKG_HOMEPAGE= CARGO_
PKG_AUTHORS='Simon Sapin <simon.sapin@exyr.org>' CARGO_PKG_VERSION=0.6.10 CARGO_PKG_VERSION_PRE= CARGO_PKG_VERSION_PATCH=10 CARGO_MANIFEST_DIR=/tmp/portage/dev-util/rustfmt-1.4.8/work/cargo_home/gentoo/smallvec-0.6.10 CARGO_PKG_VERSION_MINOR=6 CARGO_PKG_VERSION_MAJOR=0 rustc --crate-name smallvec /tmp/portage/dev-util/rustfmt-1.4.8/work/cargo_home/gentoo/smallve
c-0.6.10/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="may_dangle"' --cfg 'feature="std"' --cfg 'feature="union"' -C metadata=04cebf6205f91406 -C extra-filename=-04cebf6205f91406 --out-dir /tmp/portage/dev-util/rustfmt-1.4.8/work/rustfmt
-1.4.8/target/release/deps -L dependency=/tmp/portage/dev-util/rustfmt-1.4.8/work/rustfmt-1.4.8/target/release/deps --cap-lints warn`
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /tmp/portage/dev-util/rustfmt-1.4.8/work/cargo_home/gentoo/smallvec-0.6.10/lib.rs:33:32
   |
33 | #![cfg_attr(feature = "union", feature(untagged_unions))]                                                                                                                        
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^                               
                                                                                                                                                                                      
error[E0554]: `#![feature]` may not be used on the stable release channel                                                                                                             
  --> /tmp/portage/dev-util/rustfmt-1.4.8/work/cargo_home/gentoo/smallvec-0.6.10/lib.rs:35:37
   |                                                          
35 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^          
```

[build.log](https://github.com/rust-lang/rustfmt/files/3690332/build.log)
[emerge --info dev-lang/rust dev-util/rustfmt](https://github.com/rust-lang/rustfmt/files/3690336/emerge.info.log)

**Comment by devurandom** [comment]
P.S. In the readme, support for rust 1.24.0 is advertised.

**Comment by sinkuu** [comment]
That means pre-built rustfmt for Rust 1.24.0 is available via `rustup component`. You need nightly Rust to build rustfmt from source, as stated in [Installing from source](https://github.com/rust-lang/rustfmt#installing-from-source) section.

> To install from source (nightly required), first checkout to the tag or branch you want to install, then issue

**Comment by gjcarneiro** [comment]
Unforunately, rustup doesn't coexist with the distribution (ubuntu 20.04) installed stable Rust.  Therefore, I can't install rustup.  And it seems I can't compile from source either.  Lose/lose :(

**Comment by calebcartwright** [comment]
@gjcarneiro 

> Therefore, I can't install rustup.

It's not entirely clear to me from your comment why you wouldn't or couldn't use rustup instead, [especially since it's the recommended/official way](https://www.rust-lang.org/tools/install). FWIW I'm on ubuntu 20.04 as well and have had no issues using rustup for both stable (1.44.1) and various nightly toolchains. 

> And it seems I can't compile from source either.

The instructions and requirements for compiling the rustfmt source are described [here](https://github.com/rust-lang/rustfmt#installing-from-source), and yes like many rust tools, a recent nightly toolchain is needed for compilation. 

If you won't use rustup then I'd imagine you're going to have similar issues with other common tools like `clippy`, ide components like `rls`/`rust-analyzer`, etc., and if you can't/won't get a nightly toolchain then you won't be able to compile the rustfmt source. 

However, we are planning to start including pre-built binaries with rustfmt releases starting with the next one, though we do still strongly encourage folks to get rustfmt via rustup.

**Comment by gjcarneiro** [comment]
I am still learning Rust and don't want to use rustup because rustup installs a version of rust with unstable features turned on.  I don't want to accidentally rely on aspects of Rust that are not stable, as they may disappear or change in the future.

I would like to use stable Rust, but I would also very much like to have a formatting tool (thanks for writing it!).

I might bite the bullet and switch to rustup, or wait for rustfmt binary release, I haven't decided yet.

**Comment by glaubitz** [comment]
> It's not entirely clear to me from your comment why you wouldn't or couldn't use rustup instead, especially since it's the recommended/official way.

```rustup``` won't work for architectures for which Rust upstream does not provide binaries such as sparc64.
