### ISSUE TITLE
fails to build with latest nightly/master rustc

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#3703]
Build failure was caused by https://github.com/rust-lang/rust/pull/60340
````
   Compiling rustc-ap-arena v491.0.0
error[E0599]: no method named `cap` found for type `alloc::raw_vec::RawVec<T>` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-arena-491.0.0/lib.rs:102:47
    |
102 |                 self.start().add(self.storage.cap())
    |                                               ^^^ private field, not a method

error[E0599]: no method named `cap` found for type `alloc::raw_vec::RawVec<T>` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-arena-491.0.0/lib.rs:273:55
    |
273 |                     new_capacity = last_chunk.storage.cap();
    |                                                       ^^^ private field, not a method

error[E0599]: no method named `cap` found for type `alloc::raw_vec::RawVec<u8>` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-arena-491.0.0/lib.rs:408:55
    |
408 |                     new_capacity = last_chunk.storage.cap();
    |                                                       ^^^ private field, not a method

error: aborting due to 3 previous errors
````

**Comment by topecongiro** [comment]
Blocked by https://github.com/rust-lang/rust/pull/63036.
