### ISSUE TITLE
Rustfmt can't find module if a directory and module is named the same

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rustfmt#3794]
Reproduction, clone https://github.com/Marwes/rustfmt-bug and run `cargo fmt`.

```
error[E0583]: file not found for module `support`
 --> /home/markus/Code/rustfmt-bug/tests/test.rs:1:5
  |
1 | mod support;
  |     ^^^^^^^
  |
  = help: name the file either test/support.rs or test/support/mod.rs inside the directory "/home/markus/Code/rustfmt-bug/tests"
```

Since both `tests/test.rs` and `tests/test/` exists, rustfmt is unable to find `tests/support/mod.rs` as `mod support;` as it appears that rustfmt thinks that `test.rs` is part of the `tests/test/` module tree. This is different from how rustc/cargo sees it which compile the code happily.

I guess rustc/cargo has different module resolution for `tests/` than `src/` since rustfmt's behaviour would be correct in `src/`.

Workaround is to use `#[path = "module.rs"]` on the offending module.

**Comment by rchaser53** [comment]
How about this?
```cargo fmt -- tests/*/*.rs tests/*.rs```

**Comment by Marwes** [comment]
```
$ cargo fmt -- tests/*/*.rs tests/*.rs
error[E0583]: file not found for module `support`
 --> \\?\C:\Users\Markus\Dropbox\Programming\rustfmt-bug\tests\test.rs:1:5
  |
1 | mod support;
  |     ^^^^^^^
  |
  = help: name the file either test\support.rs or test\support\mod.rs inside the directory "\\?\C:\Users\Markus\Dropbox\Programming\rustfmt-bug\tests"

error[E0583]: file not found for module `support`
 --> \\?\C:\Users\Markus\Dropbox\Programming\rustfmt-bug\tests\test.rs:1:5
  |
1 | mod support;
  |     ^^^^^^^
  |
  = help: name the file either test\support.rs or test\support\mod.rs inside the directory "\\?\C:\Users\Markus\Dropbox\Programming\rustfmt-bug\tests"

```

**Comment by rchaser53** [comment]
Do you use Windows?
```cargo fmt -- tests/*/*.rs tests/*.rs ``` works in macOS(10.14.6).
It seems to be a problem that depends on Windows.

**Comment by Marwes** [comment]
`cargo fmt -- tests/*/*.rs tests/*.rs` was run on windows but plain `cargo fmt` breaks on linux as well.

**Comment by rchaser53** [comment]
I succeeded to reproduce the bug on ubuntu 18.04. Thank you.

**Comment by rchaser53** [comment]
The rustfmt was in my environment a bit old.
This bug is also happended on the latest rustfmt on macOS.

**Comment by topecongiro** [comment]
As a workaround, the following command may work if you are using nightly (you also need `fd`):

```shell
rustfmt --unstable-features --skip-children `fd -e rs`
```

**Comment by pnkfelix** [comment]
(It would be good if this issue's title included the detail that its specifically about resolution in cargo `tests/` directory. At least, that detail was quite relevant to me when I was trying to figure out what was wrong when I encountered it.)

**Comment by topecongiro** [comment]
This issue will be fixed in 2.0.
